#!/bin/bash
#   Copyright (C) 2016 University of Oxford
#   Part of FSL - FMRIB's Software Library
#   http://www.fmrib.ox.ac.uk/fsl
#   fsl@fmrib.ox.ac.uk
#   
#   Developed at FMRIB (Oxford Centre for Functional Magnetic Resonance
#   Imaging of the Brain), Department of Clinical Neurology, Oxford
#   University, Oxford, UK
#   
#   
#   LICENCE
#   
#   FMRIB Software Library, Release 5.0 (c) 2012, The University of
#   Oxford (the "Software")
#   
#   The Software remains the property of the University of Oxford ("the
#   University").
#   
#   The Software is distributed "AS IS" under this Licence solely for
#   non-commercial use in the hope that it will be useful, but in order
#   that the University as a charitable foundation protects its assets for
#   the benefit of its educational and research purposes, the University
#   makes clear that no condition is made or to be implied, nor is any
#   warranty given or to be implied, as to the accuracy of the Software,
#   or that it will be suitable for any particular purpose or for use
#   under any specific conditions. Furthermore, the University disclaims
#   all responsibility for the use which is made of the Software. It
#   further disclaims any liability for the outcomes arising from using
#   the Software.
#   
#   The Licensee agrees to indemnify the University and hold the
#   University harmless from and against any and all claims, damages and
#   liabilities asserted by third parties (including claims for
#   negligence) which arise directly or indirectly from the use of the
#   Software or the sale of any products based on the Software.
#   
#   No part of the Software may be reproduced, modified, transmitted or
#   transferred in any form or by any means, electronic or mechanical,
#   without the express permission of the University. The permission of
#   the University is not required if the said reproduction, modification,
#   transmission or transference is done without financial return, the
#   conditions of this Licence are imposed upon the receiver of the
#   product, and all original and amended source code is included in any
#   transmitted product. You may be held legally responsible for any
#   copyright infringement that is caused or encouraged by your failure to
#   abide by these terms and conditions.
#   
#   You are not permitted under this Licence to use this Software
#   commercially. Use for which any financial return is received shall be
#   defined as commercial use, and includes (1) integration of all or part
#   of the source code or the Software into a product for sale or license
#   by or on behalf of Licensee to third parties or (2) use of the
#   Software or any derivative of it for research with the final aim of
#   developing software products for sale or license to a third party or
#   (3) use of the Software or any derivative of it for research with the
#   final aim of developing non-software products for sale or license to a
#   third party, or (4) use of the Software to provide any service to an
#   external organisation for which payment is received. If you are
#   interested in using the Software commercially, please contact Oxford
#   University Innovation ("OUI"), the technology transfer company of the
#   University, to negotiate a licence. Contact details are:
#   Innovation@innovation.ox.ac.uk quoting reference DE/9564.
export LC_ALL=C
set -e
#set -x

if [ $# -lt 1 ] ; then
  echo "   "
  echo "Usage:  `basename $0` <bianca_output_map> <threshold> <min_cluster_size> [ <mask> ]"
  echo "   "
  echo "If only 3 inputs provided it will output the total number of clusters and the total WMH volume after applying <threshold>"
  echo "and including clusters bigger than <min_cluster_size>, where the size is expressed in number of voxels"
  echo "   "
  echo "Optional: number of clusters and  WMH volume within a mask"
  echo "<mask> = mask file (in the same space as <bianca_output_map> )"
  echo "   "
  exit 0
fi

bianca_output_map=$1
mapbasename=`basename $bianca_output_map `
mapdirname=`dirname $bianca_output_map`
mapname=`remove_ext $mapbasename .nii.gz `

threshold=$2
min_cluster_size=$3

logID=`echo $(date | awk '{print $2 $3 $4}' |  sed 's/://g')`
TMPVISDIR=`mktemp -d ./${mapname}_${logID}_XXXXXX`

# Apply threshold and binarise image
$FSLDIR/bin/fslmaths $bianca_output_map -thr $threshold -bin ${TMPVISDIR}/bianca_thr_bin

# Apply cluster size threshold 
$FSLDIR/bin/cluster -t 0.5 -i ${TMPVISDIR}/bianca_thr_bin --connectivity=26 --oindex=${TMPVISDIR}/bianca_thr_bin_idx --no_table --minextent=$min_cluster_size
$FSLDIR/bin/fslmaths ${TMPVISDIR}/bianca_thr_bin_idx -bin ${TMPVISDIR}/bianca_thr_bin_minsize_bin

# Calculate the total volume/number of clusters
total_clusters_num=`$FSLDIR/bin/cluster -t 0.5 -i ${TMPVISDIR}/bianca_thr_bin --connectivity=26 --minextent=$min_cluster_size | head -n 2 | tail -n 1 |  awk '{print $1}'`
echo " total WMH number for $bianca_output_map with threshold $threshold and minimum cluster size $min_cluster_size is $total_clusters_num"
total_volume=`$FSLDIR/bin/fslstats ${TMPVISDIR}/bianca_thr_bin_minsize_bin -V | awk '{print $2}'`
echo " total volume for $bianca_output_map with threshold $threshold and minimum cluster size $min_cluster_size is $total_volume"

# Optional: volume/number of clusters within the specified mask
if [ $# -gt 3 ] ; then
    mask=$4
    basenamemask=`basename $mask`
    namemask=`remove_ext $basenamemask .nii.gz`
    $FSLDIR/bin/fslmaths ${TMPVISDIR}/bianca_thr_bin_minsize_bin -mas $mask ${TMPVISDIR}/bianca_thr_bin_minsize_bin_masked
    # Calculate number of clusters and volume within mask
    clusters_num_in_mask=`$FSLDIR/bin/cluster  -t 0.5 -i ${TMPVISDIR}/bianca_thr_bin_minsize_bin_masked --connectivity=26 | head -n 2 | tail -n 1 |  awk '{print $1}'`
    echo " WMH number in $mask for $bianca_output_map with threshold $threshold and minimum cluster size $min_cluster_size is $clusters_num_in_mask"
    volume_in_mask=`$FSLDIR/bin/fslstats ${TMPVISDIR}/bianca_thr_bin_minsize_bin -k $mask -V | awk '{print $2}'`
    echo " WMH volume in $mask for $bianca_output_map with threshold $threshold and minimum cluster size $min_cluster_size is $volume_in_mask"
fi

rm -r ${TMPVISDIR}

