#!/bin/sh

if [ `uname` = "Darwin" ] ; then
    DYLD_LIBRARY_PATH=${FSLDIR}/bin/fslview.app/Contents/Frameworks
    DYLD_FALLBACK_LIBRARY_PATH=/opt/X11/lib
    export DYLD_LIBRARY_PATH DYLD_FALLBACK_LIBRARY_PATH
    ${FSLDIR}/bin/fslview.app/Contents/MacOS/fslview $@
fi
if [ `uname` = "Linux" ] ; then
    LD_LIBRARY_PATH=${FSLDIR}/lib:${LD_LIBRARY_PATH}
    export LD_LIBRARY_PATH
    ${FSLDIR}/bin/fslview_bin $@
fi
